### ISSUE TITLE
Support of other timezones

### ISSUE THREAD

**Issue by gitmalong** [gpgkd906/date_component#5]
Hi!

It looks like the `calculate` fn only supports `Utc`. I am in the need to calculate the diff between two dates that share the same non-UTC timezone.

If I am not mistaken I would get inaccurate results when converting the two DateTimes of my zone to Utc and then making the diff. 

https://gpgkd906.github.io/date_component/date_component/date_component/fn.calculate.html

**Comment by gpgkd906** [comment]
@gitmalong 
sorry for late reply...
Basically, for now the `calculate` fn only supports `Utc` because I thought it would be easy to convert to `Utc` using `chrono-tz`. 

>If I am not mistaken I would get inaccurate results when converting the two DateTimes of my zone to Utc and then making the diff.

I don't really understand your concern, you mean two DateTimes, to do calculations at non-UTC and at UTC will have different differential results between them?
Can you give me a concrete example?
I would love to improve on this.

**Comment by gpgkd906** [comment]
@gitmalong 
I got it.
In some timezones, for example, calculate between 2/01 and 3/01，simple convert them to UTC can lead to wrong result.
I will fix this.

**Comment by gpgkd906** [comment]
@gitmalong 
I think I had fix that.
can you check it?
